# ATTENTION! THIS ISN'T A FULLY FUNCTIONAL EXAMPLE.
# You should take portions of this example and edit the options to make
# them suitable for your use.
# This file is useful to know all the available options.
kibot:
  version: 1

globals:
  resources_dir: resources
  field_lcsc_part: "LCSC Part"
  solder_mask_color: black
  pcb_finish: ENIG

filters:
  - name: only_jlc_parts
    comment: "Only parts with JLC (LCSC Part) code"
    type: generic
    include_only:
      - column: "LCSC Part"
        regex: '^C\d+'

variants:
  - name: rotated
    comment: "Rotate for JLCPCB"
    type: kibom
    variant: rotated
    pre_transform: _rot_footprint_jlcpcb

outputs:
  - name: "pcb_print_example"
    comment: "Prints the PCB using a mechanism that is more flexible than `pdf_pcb_print` and `svg_pcb_print`."
    type: "pcb_print"
    dir: "PCBPrint"
    options:
      # [boolean=false] Add a background to the pages, see `background_color`
      add_background: true
      # [number=0] Default horizontal margin used for the autoscaling mode [mm]
      autoscale_margin_x: 0
      # [number=0] Default vertical margin used for the autoscaling mode [mm]
      autoscale_margin_y: 0
      # [string='#FFFFFF'] Color for the background when `add_background` is enabled
      background_color: "#000000"
      # [string=''] Color used for blind/buried `colored_vias`
      blind_via_color: ""
      # [string='_builtin_classic'] Selects the color theme. Only applies to KiCad 6.
      # To use the KiCad 6 default colors select `_builtin_default`.
      # Usually user colors are stored as `user`, but you can give it another name
      color_theme: "Arcana"
      # [boolean=true] Plot through-hole in a different color. Like KiCad GUI does
      colored_pads: true
      # [boolean=true] Plot vias in a different color. Like KiCad GUI does
      colored_vias: true
      # [string|list(string)='_none'] Name of the filter to mark components as not fitted.
      # A short-cut to use for simple cases where a variant is an overkill
      dnf_filter: "_none"
      # [number=360] [36,1200] Resolution (Dots Per Inch) for the output file. Most objects are vectors, but thing
      # like the the solder mask are handled as images by the conversion tools
      dpi: 600
      # [string='full'] [none,small,full] What to use to indicate the drill places, can be none, small or full (for real scale)
      drill_marks: "full"
      # [boolean=false] Add the `Edge.Cuts` to all the pages
      force_edge_cuts: false
      # [string=''] Color used for the `force_edge_cuts` option
      forced_edge_cuts_color: ""
      # [boolean=true] Used when enabling the `force_edge_cuts`, in this case this is the `use_for_center` option of the forced
      # layer
      forced_edge_cuts_use_for_center: true
      # [string='PDF'] [PDF,SVG,PNG,EPS,PS] Format for the output file/s.
      # Note that for PS you need `ghostscript` which isn't part of the default docker images
      format: "PDF"
      keep_temporal_files: true
      pages:
        - scaling: 1.0
          sheet: "%ln"
          repeat_for_layer: "F.Cu"
          repeat_layers: outers
          layers:
            - layer: Edge.Cuts
            - layer: F.Cu
            - layer: F.Mask
              color: "#ff00ff40"
            - layer: F.Paste
            - layer: F.SilkS
            - layer: F.Fab
              plot_footprint_refs: false
              plot_footprint_values: false
            - layer: Dwgs.User
        - scaling: 1.0
          sheet: "%ln"
          repeat_for_layer: "F.Cu"
          repeat_layers: inners
          layers:
            - layer: Edge.Cuts
            - layer: F.Cu
            - layer: F.SilkS
            - layer: Dwgs.User
  # - name: "Step"
  #   comment: "Exports the PCB as a 3D model."
  #   type: "step"
  #   dir: "Step"
  #   options:
  #     download: false
  #     download_lcsc: False
  #     metric_units: true
  - name: "report"
    comment: "Generates a report about the design."
    type: "report"
    dir: "report"
    options:
      converted_output: "%f-%i%I%v.%x"
      eurocircuits_class_target: "3B"
      eurocircuits_reduce_holes: 0
      template: "full"
      do_convert: true
      convert_to: "pdf"
  - name: "pdf_sch_print_dark"
    type: "pdf_sch_print"
    dir: "Schematic"
    options:
      all_pages: true
      background_color: true
      color_theme: "Arcana"
      monochrome: false
      output: "%f-%i%I%v-dark.%x"
      title: "AstraControl - Schematic"
  - name: "pdf_sch_print_default"
    type: "pdf_sch_print"
    dir: "Schematic"
    options:
      all_pages: true
      monochrome: false
      output: "%f-%i%I%v-default.%x"
      title: "AstraControl - Schematic"
  - name: "pdf_sch_print_mono"
    type: "pdf_sch_print"
    dir: "Schematic"
    options:
      all_pages: true
      monochrome: true
      output: "%f-%i%I%v-mono.%x"
      title: "AstraControl - Schematic"

  - name: JLCPCB_gerbers
    comment: Gerbers compatible with JLCPCB
    type: gerber
    dir: JLCPCB/Gerber
    options: &gerber_options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: false
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      disable_aperture_macros: true
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      line_width: 0.1
      subtract_mask_from_silk: true
    layers:
      # Note: a more generic approach is to use 'copper' but then the filenames
      # are slightly different.
      - F.Cu
      - In1.Cu
      - In2.Cu
      - B.Cu
      - F.Paste
      - B.Paste
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - Edge.Cuts

  - name: JLCPCB_drill
    comment: Drill files compatible with JLCPCB
    type: excellon
    dir: JLCPCB/Drill
    options:
      pth_and_npth_single_file: false
      pth_id: "-PTH"
      npth_id: "-NPTH"
      metric_units: true
      map: gerber
      route_mode_for_oval_holes: false
      output: "%f%i.%x"

  - name: JLCPCB
    comment: ZIP file for JLCPCB
    type: compress
    dir: JLCPCB
    options:
      files:
        - from_output: JLCPCB_gerbers
          dest: /
        - from_output: JLCPCB_drill
          dest: /

  - name: ibom
    comment: Interactive BOM
    type: ibom
    dir: IBOM
    options:
      dark_mode: true
      name_format: "index"
      extra_fields: "Datasheet"

  - name: "JLCPCB_position"
    comment: "Pick and place file, JLCPCB style"
    type: position
    dir: JLCPCB/PickAndPlace
    options:
      variant: rotated
      output: "%f_cpl_jlc.%x"
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: false
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: "Mid X"
        - id: PosY
          name: "Mid Y"
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer

  - name: "JLCPCB_bom"
    comment: "BoM for JLCPCB"
    type: bom
    dir: JLCPCB/BOM
    options:
      output: "%f_%i_jlc.%x"
      exclude_filter: "only_jlc_parts"
      ref_separator: ","
      columns:
        - field: Value
          name: Comment
        - field: References
          name: Designator
        - Footprint
        - field: "LCSC Part"
          name: "LCSC Part #"
        - field: "Quantity Per PCB"
          name: "QTY"
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true
  - name: "Markdown components table"
    comment: "All LCSC components in HTML"
    type: bom
    dir: BOM
    options:
      output: "%f_%i.%x"
      exclude_filter: "only_jlc_parts"
      columns:
        - field: Value
          name: Value
        - field: References
          name: Reference
        - field: "Extra Values"
          name: "Extra Values"
        - Footprint
        - Datasheet
        - Sheetpath
        - field: "LCSC Part"
          name: "LCSC Part #"
        - field: "Quantity Per PCB"
          name: "Quantity"
      format: "HTML"
      html:
        datasheet_as_link: "Datasheet"
        lcsc_link: true
  - name: "Test point table"
    comment: "All test points in HTML"
    type: bom
    dir: BOM
    options:
      output: "%f_%i_TP.%x"
      include_only: 
        - column: "Reference"
          regex: "TP.*"
      group_fields: ["Reference"]
      group_connectors: false
      columns:
        - field: Value
          name: Value
        - field: References
          name: Reference
        - Footprint
        - Sheetpath
      format: "HTML"

  - name: "Info"
    comment: "Records information about the current run."
    type: "info"
    dir: "CI"
    options:
      environment: "names"
      output: "%f-%i%I%v.%x"
