# ATTENTION! THIS ISN'T A FULLY FUNCTIONAL EXAMPLE.
# You should take portions of this example and edit the options to make
# them suitable for your use.
# This file is useful to know all the available options.
kibot:
  version: 1

globals:
  resources_dir: resources

filters:
  - name: only_jlc_parts
    comment: "Only parts with JLC (LCSC Part) code"
    type: generic
    include_only:
      - column: "LCSC Part"
        regex: '^C\d+'

variants:
  - name: rotated
    comment: 'Rotate for JLCPCB'
    type: kibom
    variant: rotated
    pre_transform: _rot_footprint_jlcpcb

outputs:
  - name: 'Step'
    comment: 'Exports the PCB as a 3D model.'
    type: 'step'
    dir: 'output/Step'
    options:
      # [string|list(string)='_none'] Name of the filter to mark components as not fitted.
      # A short-cut to use for simple cases where a variant is an overkill
      dnf_filter: '_none'
      # [boolean=true] Downloads missing 3D models from KiCad git.
      # Only applies to models in KISYS3DMOD and KICAD6_3DMODEL_DIR.
      # They are downloaded to a temporal directory and discarded.
      # If you want to cache the downloaded files specify a directory using the
      # KIBOT_3D_MODELS environment variable
      download: false
      # [boolean=true] In addition to try to download the 3D models from KiCad git also try to get
      # them from LCSC database. In order to work you'll need to provide the LCSC
      # part number. The field containing the LCSC part number is defined by the
      # `field_lcsc_part` global variable
      download_lcsc: true
      # [string='https://gitlab.com/kicad/libraries/kicad-packages3D/-/raw/master/'] Base URL for the KiCad 3D models
      kicad_3d_url: 'https://gitlab.com/kicad/libraries/kicad-packages3D/-/raw/master/'
      # [string=''] Text added to the end of the download URL.
      # Can be used to pass variables to the GET request, i.e. ?VAR1=VAL1&VAR2=VAL2
      kicad_3d_url_suffix: ''
      # [boolean=true] Use metric units instead of inches
      metric_units: true
      # [number=-1] The minimum distance between points to treat them as separate ones (-1 is KiCad default: 0.01 mm)
      min_distance: -1
      # [boolean=false] Used to exclude 3D models for components with 'virtual' attribute
      no_virtual: false
      # [string='grid'] Determines the coordinates origin. Using grid the coordinates are the same as you have in the design sheet.
      # The drill option uses the auxiliary reference defined by the user.
      # You can define any other origin using the format 'X,Y', i.e. '3.2,-10'
      origin: 'grid'
      # [string='%f-%i%I%v.%x'] Name for the generated STEP file (%i='3D' %x='step'). Affected by global options
      output: '%f-%i%I%v.%x'
      # [string|list(string)='_none'] Name of the filter to transform fields before applying other filters.
      # A short-cut to use for simple cases where a variant is an overkill
      pre_transform: '_none'
      # [boolean=true] Substitute STEP or IGS models with the same name in place of VRML models
      subst_models: true
      # [string=''] Board variant to apply
      variant: ''
  - name: 'pcbdraw'
    comment: 'Exports the PCB as a 2D model (SVG, PNG or JPG).'
    type: 'pcbdraw'
    dir: 'output/Render'
    options:
      # [number=300] [10,1200] Dots per inch (resolution) of the generated image
      dpi: 300
      # [string='svg'] [svg,png,jpg,bmp] Output format. Only used if no `output` is specified
      format: 'png'
      # [number|dict] Margin around the generated image [mm].
      # Using a number the margin is the same in the four directions
      margin:
        # [number=0] Bottom margin [mm]
        bottom: 0
        # [number=0] Left margin [mm]
        left: 0
        # [number=0] Right margin [mm]
        right: 0
        # [number=0] Top margin [mm]
        top: 0
      # [number=0.15] [0,10] Width of the trace to draw the PCB border [mm].
      # Note this also affects the drill holes
      outline_width: 0.15
      show_solderpaste: false
      # [string='%f-%i%I%v.%x'] Name for the generated file. Affected by global options
      output: '%f-%i%I%v.%x'
      # [boolean=false] Show placeholder for missing components
      placeholder: true
      style:
        # [string='#208b47'] Color for the board without copper (covered by solder mask)
        board: '#208b47'
        # [string='#cabb3e'] Color for the PCB core (not covered by solder mask)
        clad: '#d4af37'
        # [string='#285e3a'] Color for the copper zones (covered by solder mask)
        copper: '#285e3a'
        # [boolean=false] Highlight over the component (not under)
        highlight_on_top: false
        # [number=1.5] [0,1000] How much the highlight extends around the component [mm]
        highlight_padding: 1.5
        # [string='stroke:none;fill:#ff0000;opacity:0.5;'] SVG code for the highlight style
        highlight_style: 'stroke:none;fill:#ff0000;opacity:0.5;'
        # [string='#000000'] Color for the outline
        outline: '#000000'
        # [string='#8b898c'] Color for the exposed pads (metal finish)
        pads: '#8b898c'
        # [string='#d5dce4'] Color for the silk screen
        silk: '#000000'
        # [string='#bf2600'] Color for the V-CUTS
        vcut: '#bf2600'
      # [string='visible'] [visible,all,none] Using visible only the warnings about components in the visible side are generated
      warnings: 'visible'
  - name: 'report_example'
    comment: 'Generates a report about the design.'
    type: 'report'
    dir: 'output/Report'
    options:
      # [string='markdown'] Original format for the report conversion. Current templates are `markdown`. See `do_convert`
      convert_from: 'markdown'
      # [string='pdf'] Target format for the report conversion. See `do_convert`
      convert_to: 'pdf'
      # [string='%f-%i%I%v.%x'] Converted output file name (%i='report', %x=`convert_to`).
      # Note that the extension should match the `convert_to` value. Affected by global options
      converted_output: '%f-%i%I%v.%x'
      # [boolean=false] Run `Pandoc` to convert the report. Note that Pandoc must be installed.
      # The conversion is done assuming the report is in `convert_from` format.
      # The output file will be in `convert_to` format.
      # The available formats depends on the `Pandoc` installation.
      # In CI/CD environments: the `kicad_auto_test` docker image contains it.
      # In Debian/Ubuntu environments: install `pandoc`, `texlive`, `texlive-latex-base` and `texlive-latex-recommended`
      do_convert: false
      # [string='10F'] Which Eurocircuits class are we aiming at
      eurocircuits_class_target: '10F'
      # [number=0.45] When computing the Eurocircuits category: Final holes sizes smaller or equal to this given
      # diameter can be reduced to accommodate the correct annular ring values.
      # Use 0 to disable it
      eurocircuits_reduce_holes: 0.45
      # [string='%f-%i%I%v.%x'] Output file name (%i='report', %x='txt'). Affected by global options
      output: '%f-%i%I%v.%x'
      # [string='full'] Name for one of the internal templates (full, full_svg, simple) or a custom template file.
      # Environment variables and ~ are allowed.
      # Note: when converting to PDF PanDoc can fail on some Unicode values (use `simple_ASCII`)
      template: 'full'
  - name: "pdf_sch_print"
    comment: "Exports the schematic to the most common exchange format. Suitable for printing."
    type: "pdf_sch_print"
    dir: "output"
    options:
      # [boolean=true] Generate with all hierarchical sheets
      all_pages: true
      # [boolean=false] Use the background color from the `color_theme` (KiCad 6)
      background_color: true
      # [string=''] Color theme used, this must exist in the KiCad config (KiCad 6)
      color_theme: "Arcana"
      # [string|list(string)='_none'] Name of the filter to mark components as not fitted.
      # A short-cut to use for simple cases where a variant is an overkill
      dnf_filter: "_none"
      # [boolean=true] Include the frame and title block
      frame: true
      # [boolean=false] Generate a monochromatic output
      monochrome: false
      # [string='%f-%i%I%v.%x'] Filename for the output PDF (%i=schematic, %x=pdf). Affected by global options
      output: "%f-%i%I%v.%x"
      # [string=''] Worksheet file (.kicad_wks) to use. Leave empty to use the one specified in the project.
      # This option works only when you print the toplevel sheet of a project and the project
      # file is available
      sheet_reference_layout: ""
      # [string=''] Text used to replace the sheet title. %VALUE expansions are allowed.
      # If it starts with `+` the text is concatenated
      title: ""
      # [string=''] Board variant to apply.
      # Not fitted components are crossed
      variant: ""
      # Info:
  - name: JLCPCB_gerbers
    comment: Gerbers compatible with JLCPCB
    type: gerber
    dir: output/JLCPCB/Gerber
    options: &gerber_options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: false
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      disable_aperture_macros: true
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      line_width: 0.1
      subtract_mask_from_silk: true
    layers:
      # Note: a more generic approach is to use 'copper' but then the filenames
      # are slightly different.
      - F.Cu
      - In1.Cu
      - In2.Cu
      - B.Cu
      - F.Paste
      - B.Paste
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - Edge.Cuts

  - name: JLCPCB_drill
    comment: Drill files compatible with JLCPCB
    type: excellon
    dir: output/JLCPCB/Drill
    options:
      pth_and_npth_single_file: false
      pth_id: '-PTH'
      npth_id: '-NPTH'
      metric_units: true
      map: gerber
      route_mode_for_oval_holes: false
      output: "%f%i.%x"

  - name: JLCPCB
    comment: ZIP file for JLCPCB
    type: compress
    dir: output/JLCPCB
    options:
      files:
        - from_output: JLCPCB_gerbers
          dest: /
        - from_output: JLCPCB_drill
          dest: /

  - name: ibom
    comment: Interactive BOM
    type: ibom 
    dir: output/IBOM
    options:
      dark_mode: true
      name_format: 'index'

  - name: 'JLCPCB_position'
    comment: "Pick and place file, JLCPCB style"
    type: position
    dir: output/JLCPCB/PickAndPlace
    options:
      variant: rotated
      output: '%f_cpl_jlc.%x'
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: false
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: "Mid X"
        - id: PosY
          name: "Mid Y"
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer

  - name: 'JLCPCB_bom'
    comment: "BoM for JLCPCB"
    type: bom
    dir: output/JLCPCB/BOM    
    options:
      output: '%f_%i_jlc.%x'
      exclude_filter: 'only_jlc_parts'
      ref_separator: ','
      columns:
        - field: Value
          name: Comment
        - field: References
          name: Designator
        - Footprint
        - field: 'LCSC Part'
          name: 'LCSC Part #'
        - field: 'Quantity Per PCB'
          name: 'QTY'
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true
  # It can be used to know more about the environment used to generate the files.
  # Please don't rely on the way things are reported, its content could change,
  # adding or removing information
  - name: "Info"
    comment: "Records information about the current run."
    type: "info"
    dir: "output"
    options:
      # [string='names'] [names,none,full] List environment variables.
      # IMPORTANT: Don't use `full` unless you know you are not leaking sensitive information
      environment: "names"
      # [string='%f-%i%I%v.%x'] Filename for the output (%i=info, %x=txt). Affected by global options
      output: "%f-%i%I%v.%x"
