name: CI

on: push

jobs:
  Documents:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto_full:latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S')"
      - uses: actions/checkout@v4
        with:
          # So we can run a diff between last 2 changes
          fetch-depth: "0"

      - name: Run Kibot
        run: |
          kibot -vvv -d output -c config.kibot.yaml -e AstraControl.kicad_sch -b AstraControl.kicad_pcb
          mkdir -p Generated/Report
          find .
          cp ./output/Report/AstraControl-report.txt Generated/Report/Report.md

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AstraControl-${{ steps.date.outputs.date }}
          path: output
      - name: Submit to Repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: "[skip ci] Update repository with generated items"

          # Optional. Local file path to the repository.
          # Defaults to the root of the repository.
          repository: .

          # Optional commit user and author settings
          commit_user_name: GitHub Actions Bot # defaults to "github-actions[bot]"
  Render:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto_full:latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S')"
      - uses: actions/checkout@v4
        with:
          # So we can run a diff between last 2 changes
          fetch-depth: "0"

      - name: Run Kibot
        run: |
          kibot -vvv -d output -c 3DRender.kibot.yaml -e AstraControl.kicad_sch -b AstraControl.kicad_pcb

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AstraControl-3DRender-${{ steps.date.outputs.date }}
          path: output
