name: CI

on: push

jobs:
  ERC:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run ERC
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: Generated
        skip: run_drc
        targets: __NONE__

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: ERC_Output
        path: Generated