name: CI

on: push

jobs:
  ERC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: INTI-CMNB/KiBot@v2_k8
        run: |
          ls -l /github/home/.config/kicad/
          ls -l /github/home/.config/kicad/8.0/colors
          cp themes/Arcana.json /github/home/.config/kicad/8.0/colors
          ls -l /github/home/.config/kicad/8.0/colors
        with:
          # Required - kibot config file
          config: config.kibot.yaml
          verbose: 3
          # optional - prefix to output defined in config
          dir: output
          # optional - schematic file
          schema: "AstraControl.kicad_sch"
          # optional - PCB design file
          board: "AstraControl.kicad_pcb"
      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output
